//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.01 at 11:43:42 PM IST 
//


package interstellar.za.co.discovery.routes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originPlanet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="destinationPlanet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "originPlanet",
    "destinationPlanet"
})
@XmlRootElement(name = "GetRoutesRequest")
public class GetRoutesRequest {

    @XmlElement(required = true)
    protected String originPlanet;
    @XmlElement(required = true)
    protected String destinationPlanet;

    /**
     * Gets the value of the originPlanet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginPlanet() {
        return originPlanet;
    }

    /**
     * Sets the value of the originPlanet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginPlanet(String value) {
        this.originPlanet = value;
    }

    /**
     * Gets the value of the destinationPlanet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationPlanet() {
        return destinationPlanet;
    }

    /**
     * Sets the value of the destinationPlanet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationPlanet(String value) {
        this.destinationPlanet = value;
    }

}
