//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.01 at 11:43:42 PM IST 
//


package interstellar.za.co.discovery.routes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RoutesDetails" type="{http://discovery.co.za.interstellar/routes}RouteDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "routesDetails"
})
@XmlRootElement(name = "GetRoutesDetailsResponse")
public class GetRoutesDetailsResponse {

    @XmlElement(name = "RoutesDetails", required = true)
    protected RouteDetails routesDetails;

    /**
     * Gets the value of the routesDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RouteDetails }
     *     
     */
    public RouteDetails getRoutesDetails() {
        return routesDetails;
    }

    /**
     * Sets the value of the routesDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteDetails }
     *     
     */
    public void setRoutesDetails(RouteDetails value) {
        this.routesDetails = value;
    }

}
