//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.01 at 11:43:42 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://discovery.co.za.interstellar/routes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package interstellar.za.co.discovery.routes;
